### ISSUE TITLE
Server start error

### ISSUE THREAD

**Issue by metadeus** [acsl-mipt/vagrant-multiple-sitl#1]
vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:~$ ./start-multiple-px4-gzserver.sh 
./gazebo_export.sh: line 1: /usr/share/gazebo-6.5/setup.sh: No such file or directory
vagrant@vagrant-ubuntu-trusty-64:~$ terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

**Comment by korotkoves** [comment]
fixed by https://github.com/acsl-mipt/vagrant-multiple-sitl/commit/fcf47e86e8ca11729a0f5d8ac8c0f630ce88ed0d

**Comment by metadeus** [comment]
vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:~$ ./start-multiple-px4-gzserver.sh 
vagrant@vagrant-ubuntu-trusty-64:~$ terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

**Comment by korotkoves** [comment]
possible locale problems
