### ISSUE TITLE
Не загружается на Ubuntu 16.04

### ISSUE THREAD

**Issue by metadeus** [acsl-mipt/vagrant-multiple-sitl#2]
metadeus@bubunta:~/projects/ACSL/vagrant-multiple-sitl$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20160406.0.0'. The latest is version '20160518.0.0'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: vagrant-multiple-sitl_default_1463919064338_47429
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by korotkoves** [comment]
Проверил на Ubuntu 16.04:
sudo apt-get update
sudo apt-get install virtualbox vagrant
git clone https://github.com/acsl-mipt/vagrant-multiple-sitl
cd vagrant-multiple-sitl
vagrant up
vagrant ssh
Все ок, закрываю.
