### ISSUE TITLE
Предлагаю сделать ротацию логов или как то ограничить их размер

### ISSUE THREAD

**Issue by metadeus** [acsl-mipt/vagrant-multiple-sitl#4]
Запущенная виртуалка постоянно пишет логи и за ночь сжирает десятки гигабайт под свои данные. Можно это ограничить как-то?

**Comment by korotkoves** [comment]
https://github.com/acsl-mipt/Firmware/commit/c5bbc611e21394a7bf7a41835794863a408bc2fc
